services:
  users-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5156:80"
      - "7010:443"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ERSMS_POSTGRESQL_CONNECTION_STRING=Host=postgres;Port=5432;Database=usersdb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    volumes:
      - ../logs/:/app/logs/:rw
    networks:
      - usersnet

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    networks:
      - usersnet
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  usersnet:

volumes:
  postgres-data:
